
// public enum EmulatorEvent {
//     EMULATOR_CONNECTED,
//     EMULATOR_UNCHANGED,
//     EMULATOR_DISCONNECTED,
//     EMULATOR_LOCATION_UPDATED,
//     EMULATOR_STATUS_UPDATED,
//     EMULATOR_TRIP_STARTED,
//     EMULATOR_TRIP_ENDED,
//     EMULATOR_TRIP_CANCELLED,
//     EMULATOR_TRIP_PAUSED,
//     EMULATOR_TRIP_RESUMED,
//     EMULATOR_TRIP_DETAILS_UPDATED,
// }

export enum EmulatorEvent {
    EMULATOR_CONNECTED = "EMULATOR_CONNECTED",
    EMULATOR_CONNECTED_NO_TRIP = "EMULATOR_CONNECTED_NO_TRIP",
    EMULATOR_LOCATION_UPDATED = "EMULATOR_LOCATION_UPDATED",
    EMULATOR_TRIP_CANCELLED = "EMULATOR_TRIP_CANCELLED",
    EMULATOR_TRIP_DETAILS_UPDATED = "EMULATOR_TRIP_DETAILS_UPDATED",
}